### DISCUSSION TITLE
Loki test ci on Bitbucket pipeline

### DISCUSSION THREAD

**Discussion by anthodb** [oblador/loki#511] [Q&A] [answered]
Hello everyone! 
Does anyone have had success to make the loki visual testing pipeline work on bitbucket pipeline?
I'm using 0.35.0.

On Bitbucket I'm using this step : 
```
 - step: &test-step
        name: test project
        caches:
          - npm
        script:
          - cd React_app
          - npm ci --prefer-offline
          - npm run build-storybook && loki --requireReference --reactUri file:./storybook-static
        services:
          - docker
        artifacts:
          - .loki/**
```

The pipeline fails with this error : 

```
RUNS chrome.docker
RUNS chrome.docker/PREPARE
PASS chrome.docker/PREPARE
RUNS chrome.docker/START
FAIL chrome.docker/START: Command failed with exit code 125: docker run --rm -d -P --security-opt=seccomp=unconfined --add-host=host.docker.internal:host-gateway --shm-size=1g -p 10862:10862 yukinying/chrome-headless-browser-stable:118.0.5993.117 --disable-datasaver-prompt --no-first-run --disable-extensions --remote-debugging-address=0.0.0.0 --remote-debugging-port=10862 --headless --disable-gpu --hide-scrollbars
docker: Error response from daemon: authorization denied by plugin pipelines: --security-opt is not allowed.
See 'docker run --help'.
FAIL chrome.docker: Some tasks failed to run
Some visual tests failed to run
```

Issue is here : --security-opt is not allowed.

Seems like I'm stuck here, any help would be much appreciated!
