### ISSUE TITLE
[HELP] Loki on react-native android device

### ISSUE THREAD

**Issue by LuizFBrisighello** [oblador/loki#180]
I'm having trouble runing loki in my react-native project deving on android device.
I followed loki's [Getting Started](https://loki.js.org/getting-started.html) docs

`yarn loki init` sets:
```
  "loki": {
    "configurations": {
      "ios.iphone7": {
        "target": "ios.simulator"
      }
    }
  }
```
Even tho im using a android device.

`yarn loki update` at step 3 returns me:

```
loki update v0.18.1
  ❯ iOS Simulator
    ✖ Start
      → Failed preparing for loki. Make sure the 
…
      Fetch list of stories
      Test ios.iphone7
      Stop
Failed preparing for loki. Make sure the app is configured and running in storybook mode. 
```
But im already running `storybook` on my device.

Thats my story file structure as recommended by storybook docs:
```

•
└── src
    └── components
        └── button
            ├── button.js
            └── button.stories.js
```
 And finally thats my `storybook.js` file:

```
import { AppRegistry } from 'react-native'
import { getStorybookUI, configure } from '@storybook/react-native'
import 'loki/configure-react-native'

const stories = () => ([
  require(...),
  require(...),
  require(...),
  require(...),
  require(...),
  require(...),
])

configure(stories, module)

const StorybookUIRoot = getStorybookUI({ port: 7007, host: 'localhost' })

AppRegistry.registerComponent('RNApp', () => StorybookUIRoot)

export default StorybookUIRoot
```

**Comment by LuizFBrisighello** [comment]
Tried 
```
  "loki": {
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.app",
        "width": 1366,
        "height": 768
      }
    }
  }
```

and got:
```
loki update v0.18.1
  ❯ Chrome (app)
    ✔ Start
    ✖ Fetch list of stories
      → Failed fetching stories because the server is down
      Test chrome.laptop
      Stop
Failed fetching stories because the server is down
```

**Comment by alanbueno** [comment]
Might have something to do with #184. Good luck!

**Comment by deecewan** [comment]
If you're trying to run on android, you need a different configuration:

```
"configurations": {
  "android": {
    "target": "android.emulator"
  }
}
```

**Comment by LuizFBrisighello** [comment]
> If you're trying to run on android, you need a different configuration:
> 
> ```
> "configurations": {
>   "android": {
>     "target": "android.emulator"
>   }
> }
> ```

Even if im trying it on a physical android device?

**Comment by ETLopes** [comment]
Any new on this one? I'm having issues running Loki on iOS and having the same issue. 
```
  visual-regression-test:
    macos:
      xcode: "12.4.0"
    steps:
      - checkout-and-attach-workspace
      - set_node_version
      - run:
          name: Donwload Images
          command: git lfs pull
      - react-native/pod_install
      - run:
          background: true
          name: Start Storybook (Background)
          command: yarn storybook
      - react-native/ios_simulator_start:
          device: "iPhone 11"
      - run:
          name: Start Mobile Store
          command: yarn ios
      - run:
          name: Loki test
          command: yarn loki:test-ci
```

And the output is the same:

```
yarn run v1.22.10
$ yarn loki test --verboseRenderer --port 7007
$ /Users/distiller/project/node_modules/.bin/loki test --verboseRenderer --port 7007
loki test v0.28.1
RUNS ios.simulator
RUNS ios.simulator/START
FAIL ios.simulator/START: Failed preparing for loki. Make sure the app is configured and running in storybook mode.
FAIL ios.simulator: Some tasks failed to run
Some visual tests failed to run
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1

```
