### ISSUE TITLE
Loki with Docker in Docker: chrome.docker 

### ISSUE THREAD

**Issue by rwieruch** [oblador/loki#204]
First of all, thanks for this great project. It's exactly what I have been looking for.

Locally everything works like a charm. However, once I try to run it on Gitlab's CI, I get the following error:

```
> loki test laptop --requireReference --reactUri file:./dist
 loki test v0.18.1
 [17:45:31] Chrome (app) [started]
 [17:45:31] Start [started]
 [17:45:31] Start [failed]
 [17:45:31] → The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
 [17:45:31] Chrome (app) [failed]
 [17:45:31] → The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
 The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
```

The script I am trying to run is the following:

```
"loki:test": "loki test laptop --requireReference --reactUri file:./dist",
```

Is there anything I can do to make it work in my CI? Maybe there is already a [docker image](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html) that I could use in my `.gitlab-ci.yml`:

```
image: node:8.11.0

stages:
  - test

test:
  stage: test
  before_script:
    - npm install && npm run storybook-build
  script:
    - npm run loki:test
```

package.json

```
  "loki": {
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.app",
        "width": 1366,
        "height": 768,
        "deviceScaleFactor": 1,
        "mobile": false
      },
      "chrome.iphone7": {
        "target": "chrome.app",
        "preset": "iPhone 7"
      }
    }
  }
```

**Comment by rwieruch** [comment]
Used `image: markhobson/node-chrome` as image now. Tests are running, but ~50% of them are failing. Could there be a difference between running the tests locally and on the CI? Should I run the local tests in a Docker container too?

**Comment by rwieruch** [comment]
Turns out I have to Dockerize my application locally for getting the same test results. Give me some time and I will fix this myself. Will leave something here as documentation for others 🚀

**Comment by rwieruch** [comment]
Dockerized the application with a *Dockerfile*:

```
FROM markhobson/node-chrome

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# If you are building your code for production
# RUN npm ci --only=production
# RUN npm CI=true

# Bundle app source
COPY ./ ./
```

And used `docker-compose` with a *docker-compose.yml* to run the loki test (here: `loki-test`) and to update (here: `loki-update`) the reference files.

```
version: '3'

services:
  dev:
    build:
      context: .
    ports:
      - 9001:9001
    command: npm run storybook
    volumes:
      - './src:/usr/app/src'

  test:
    build:
      context: .
    environment:
      - CI=true
    command: npm test

  loki-test:
    build:
      context: .
    environment:
      - CI=true
    command: npm run loki:test
    volumes:
      - './.loki:/usr/app/.loki'

  loki-update:
    build:
      context: .
    environment:
      - CI=true
    command: npm run loki:update
    volumes:
      - './.loki:/usr/app/.loki'
```

Last question: So far, everything can be done with `loki test` and `loki update`. It's not super clear when to use `loki approve` if `loki update` is already doing what I am looking for.

Thanks again for this awesome project.

**Comment by rwieruch** [comment]
I ended up with 1% flaky tests. I guess even though I run everything with Docker now, the `chrome.app` flag from Loki should be turned into `chrome.docker`. Now I ended up with https://github.com/oblador/loki/issues/130 Is there no ready-to-go Dockerfile for Loki?

**Comment by rwieruch** [comment]
Used the following Docker Image for `chrome.docker`, because it comes with Docker in Docker and Node/Chrome:

```
FROM soon/dind-node-build-runner

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# If you are building your code for production
# RUN npm ci --only=production
# RUN npm CI=true

# Bundle app source
COPY ./ ./
```

With the following Docker Compose with `privileged` (requirement of Image):

```
version: '3'

services:
  dev:
    privileged: true
    build:
      context: .
    ports:
      - 9001:9001
    command: npm run storybook
    volumes:
      - './src:/usr/app/src'

  test:
    privileged: true
    build:
      context: .
    environment:
      - CI=true
    command: npm test

  loki-test:
    privileged: true
    build:
      context: .
    environment:
      - CI=true
    command: npm run loki:test
    volumes:
      - './.loki:/usr/app/.loki'

  loki-update:
    privileged: true
    build:
      context: .
    environment:
      - CI=true
    command: npm run loki:update
    volumes:
      - './.loki:/usr/app/.loki'
```

Also I had to adjust the npm script to use `chromeDockerWithoutSeccomp`, otherwise I ran into https://github.com/oblador/loki/issues/154:

```
"loki:test": "loki test laptop --chromeDockerWithoutSeccomp --requireReference --reactUri file:./dist",
```

Executing everything with `docker-compose build loki-test && docker-compose run loki-test` leads into an error for the second command:

```
> loki test laptop --chromeDockerWithoutSeccomp --requireReference --reactUri file:./dist

loki test v0.18.1
[09:52:38] Chrome (docker) [started]
[09:52:38] Prepare environment [started]
[09:54:44] Prepare environment [completed]
[09:54:44] Start [started]
[09:54:44] Start [failed]
[09:54:44] → Command failed: docker run --rm -d -P -v /usr/app/dist:/var/loki --shm-size=1g -p 33325:33325 yukinying/chrome-headless:63.0.3230.2 --disable-datasaver-prompt --no-first-run --disable-extensions --remote-debugging-address=0.0.0.0 --remote-debugging-port=33325 --headless --disable-gpu --hide-scrollbars
Conflicting options: --rm and -d
```

I guess it's related to https://github.com/oblador/loki/blob/5a2cffddf7654cf6f2a7eed74000487d53ef00dc/packages/target-chrome-docker/src/create-chrome-docker-target.js#L51

I am at a point where I just want to use `chrome.app` again; with an undesired `chromeTolerance `. Not entirely sure why I have set up Docker in the first place, because there are still different outputs locally and on CI. Seems to be this Docker in Docker thing, but I have no clue how to get any further :(
