### ISSUE TITLE
Github actions fail

### ISSUE THREAD

**Issue by nrakochy** [oblador/loki#315]
Hi there, 

Thanks for the great tool 👍 , and I apologize in advance, as I can see [this issue has been raised previously](https://github.com/oblador/loki/issues/309).

Any chance you could post a working version of the config that works w/ GH Actions? I can run locally but not on CI.
I have tried multiple variations of the example config, but my GH-action-fu is weak. 

Loki config
```js
module.exports = {
    configurations: {
        desktop: {
            target: "chrome.docker", /// also tried "chrome.app"
            width: 1366,
            height: 768,
            deviceScaleFactor: 1,
            mobile: false
        }
    }
};
``` 

Relevant GH config
```
   - name: Generate Diff
              env:
                  DIFF_LIST: ${{ needs.check_for_changed_components.outputs.file_list }}
              id: generate
              shell: bash
              run: "${GITHUB_WORKSPACE}/scripts/pr-generate-visual-diff.sh"
```

and the script itself in bash
```js
  yarn build-storybook --quiet
  yarn loki update --reactUri file:./storybook-static --storiesFilter=$1 --silent
```

It fails variously, `Docker is not installed` (via `chrome.docker`), `CHROME_PATH must be defined` (via `chrome.app`).

I suspect I need to add a `services` config, but the relationship between docker and loki is rather opaque in my mind. I appreciate any help. Many thanks!
