### ISSUE TITLE
GitlabCI

### ISSUE THREAD

**Issue by frosato-ekino** [oblador/loki#74]
First of all, thank you for this great tool, I really like it! 

However, I'm having difficulties to make it run in **GitlabCI**. Target `chome.docker` requires Docker to be installed because it's pulling it own docker image and this does not combine well with GitlabCI.
That means I need to provide to my CI Job a Docker image with Node and Docker installed. 
Since my skills with docker are limited, I was not able to make it work so far. 

```
storybook-test:
  stage: test
  tags: [docker]
  image: a-docker-image/with-node-and-docker
  script:
    - npm i
    - npx build-storybook -s ./public
    - npx loki --requireReference --reactUri file:./public
```
Am I missing something? Do you have any advice to make it work on GitlabCI?

nb: `a-docker-image/with-node-and-docker` is not a real image, this is just ti illustrate the snippet
