### ISSUE TITLE
Running loki in CI setup

### ISSUE THREAD

**Issue by leenasn** [oblador/loki#9]
Hi,

What is the best way to run loki in CI like CircleCI or Codeship? 

Can it run across different simulators/emulators?

Thanks,
Leena

**Comment by felquis** [comment]
I'm using travis CI

**Comment by felquis** [comment]
@leenasn take a look at #10

**Comment by felquis** [comment]
@leenasn @oblador has documented it on #11, its now on master.

**Comment by oblador** [comment]
I'm working on react-native too, but waiting on circle ci to give me a macos plan.

**Comment by nuc** [comment]
That config works for us on CircleCI:

```
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install node@9.6.1
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v9.6.1
            nvm alias default v9.6.1
            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

      - run: node -v
      - run: npm i -g yarn
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn build-storybook && yarn loki --requireReference --reactUri file:./storybook-static
```

Though we ended up getting that: https://github.com/oblador/loki/issues/55
