### ISSUE TITLE
Gitlabs CI timeout on debugger

### ISSUE THREAD

**Issue by geraintf** [oblador/loki#92]
I am getting a timeout error when trying to run loki in gitlabs CI.

`Timed out waiting for Chrome Debugger to appear on  172.x.x.x:42676`

Using this version of Loki: https://github.com/oblador/loki/pull/90

.gitlab-ci.yml
```
visual-regression-test:
  <<: *apply_runner_tags
  <<: *skip_on_tags
  stage: test
  image: an-internal- (this image installs node 8.x and installs docker via apk add --update --no-cache docker)
  script:
    - cd packages/ui-components
    - docker info
    - npm run vr:ci-test (build-storybook && loki --requireReference --reactUri file:./storybook-static)
```

loki config
```
  "loki": {
    "storiesFilter": "^(?:(?!(Spinner)|(Carousel)|(Scenes)).)*$",
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.docker",
        "width": 1200,
        "height": 768
      },
      "chrome.iphone7": {
        "target": "chrome.docker",
        "preset": "iPhone 7"
      }
    }
  }
```

![screen shot 2018-07-20 at 16 55 21](https://user-images.githubusercontent.com/13432246/43012624-86b48b52-8c3e-11e8-93d1-475c0e79e48d.png)

I believe it comes from this line https://github.com/oblador/loki/pull/90/files#diff-b75c1e1e6b0fa125e76a9f03fe7716c5R171, it seems that maybe to it thinks its found docker (or maybe it has) but the ip/port is wrong.
